eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: index-zuul-service
zuul:
  routes:
    api-a:
      path: /api-codes/**
      serviceId: INDEX-CODES-SERVICE
    # 所有的访问 /api-codes/ 的请求，都会自动转到 INDEX-CODES-SERVICE 去。
    # 而 INDEX-CODES-SERVICE 有3个，就会在这3个之间来回切换。
    #    http://127:0:0:1:8031/api-codes/codes  等同于  http://127.0.0.1:8011/codes
    api-b:
      path: /api-backtest/**
      serviceId: TREND-TRADING-BACKTEST-SERVICE
    api-c:
      path: /api-view/**
      serviceId: TREND-TRADING-BACKTEST-VIEW